apiVersion: v1
kind: Service
metadata:
  namespace: macrostack
  name: gateway
  labels:
    app: gateway
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
  selector:
    app: gateway
